[base]
package = morph
env_name = morph
vec = native
policy_name = Policy
# rnn_name = Recurrent

[env]
motion_file = "/workspace/dataset/AMASS/amass_train_take6_upright.pkl"
has_self_collision = True
num_envs = 2048

[train]
seed = 1
torch_deterministic = True
device = cuda

cpu_offload = False
compile = False
norm_adv = True
target_kl = None

total_timesteps = 10_000_000
eval_timesteps = 100_000

num_envs = 1
batch_size = 65536
minibatch_size = 16384

update_epochs = 5
bptt_horizon = 16
learning_rate = 0.00002
anneal_lr = False
gae_lambda = 0.99
gamma = 0.95

clip_coef = 0.2
clip_vloss = True
vf_coef = 5.0
vf_clip_coef = 0.2
max_grad_norm = 0.5
ent_coef = 0.0
disc_coef = 5.0 

checkpoint_interval = 1000
