[base]
package = ocean
env_name = puffer_tower_climb
policy_name = TowerClimb
rnn_name = TowerClimbLSTM

[vec]
num_envs = 4

[env]
num_envs = 1024
reward_climb_row = 0.15
reward_fall_row = -0.06
reward_illegal_move = -0.006
reward_move_block = 0.02

[train]
# https://wandb.ai/kywch/pufferlib/runs/b8ym2mvu/overview
total_timesteps = 600_000_000
anneal_lr = True
min_lr_ratio = 0.1
batch_size = auto
bptt_horizon = 64
minibatch_size = 65536

clip_coef = 0.58
ent_coef = 0.003
gae_lambda = 0.71
gamma = 0.94
vf_clip_coef = 5.0
vf_coef = 4.6

learning_rate = 0.045
max_grad_norm = 5.0

adam_beta1 = 0.56
adam_beta2 = 0.999
adam_eps = 1.5e-8
prio_alpha = 0.99
prio_beta0 = 0.98
vtrace_c_clip = 4.2
vtrace_rho_clip = 5.0

[sweep]
metric = perf
metric_distribution = percentile

[sweep.train.total_timesteps]
distribution = uniform
min = 100_000_000
max = 2_000_000_000
scale = 0.5

[sweep.train.min_lr_ratio]
distribution = uniform
min = 0
max = 0.5
scale = auto

[sweep.env.reward_climb_row]
distribution = uniform
min = 0.0
max = 1.0
scale = auto

[sweep.env.reward_fall_row]
distribution = uniform
min = -1.0
max = 0.0
scale = auto

[sweep.env.reward_illegal_move]
distribution = uniform
min = -1e-2
max = -1e-4
scale = auto

[sweep.env.reward_move_block]
distribution = uniform
min = 0.0
max = 1.0
scale = auto
